### ISSUE TITLE
Changing password in Scalarm

### ISSUE THREAD

**Issue by grzanka** [Scalarm/scalarm#2]
I have a question: 
I log in to Scalarm using PLGRID authentication.
if I change password in Scalarm (https://system.scalarm.com/user_controller/account), will it change my password in PLGRID ?

**Comment by kliput** [comment]
Hello,

> if I change password in Scalarm (https://system.scalarm.com/user_controller/account), will it change my password in PLGRID ?

**No**, we would never change your credentials on computational resources from Scalarm.

To explain, there are two types of credentials on the page you linked:
- Scalarm credentials - the form on the top of the page - these credentials are only used to log in into Scalarm using "Login with BasicAuth" button and for using HTTP API (also with BasicAuth). I think you mean these credentials in your question.
- Computational resources credentials - the credentials that can be used to log into computational resources (eg. PLGrid User Interfaces). The credentials are validated on submit but entering them cannot change original PLGrid credentials.

**Comment by grzanka** [comment]
I would feel more comfortable if this would be more clearly expressed in the "account management panel".

Couldn't you simple hide "changing password field" if user is logged using "Computational resources credentials" (i.e. PLGRID) ?

**Comment by kliput** [comment]
I think it's an interesting idea to inform user that these credentials are used for BasicAuth only and the user logged in with other authentication method. I think that hiding this field is not necessary if we put a clear information there.
@grzanka - thanks for your feedback.
@dkrol - we can discuss a content of the message.

**Comment by dkrol** [comment]
We can put a better message here, but it is important to have this functionality. By using openid-based authentication you are limited to web browser only, while with basic auth you can also use other clients as well, e.g. command line and HTTP-based API.
