### ISSUE TITLE
Scalarm forgets my PLGRID credentials

### ISSUE THREAD

**Issue by grzanka** [Scalarm/scalarm#3]
I am trying to run a simple simulation with a simple "mistake".
First I add only few resources, then realize that I need more for my experiment.
When clicking "Add computing power" for second time I am asked to provide credentials to Prometheus cluster.

See my session here:
https://www.youtube.com/watch?v=aaYf9a0XetE&feature=youtu.be

**Comment by dkrol** [comment]
This looks like a bug. We will try to fix it as soon as possible.

**Comment by dkrol** [comment]
This should be fixed now.
