### ISSUE TITLE
Random uniform distribution of parameters

### ISSUE THREAD

**Issue by grzanka** [Scalarm/scalarm#5]
I would like to perform a parameter study, choosing some of the input parameters from random uniform distribution.

I've found an option "discrete uniform transform" but it is not clear how to use it.

Where can I specify number of samples generated per interval ?

**Comment by dkrol** [comment]
This parametrization is rather a basic one. When you select the uniform distribution you can specify minimum and maximum values and Scalarm will generate a single value for this parameter based on the specified distribution.

If you need some specific parametrization, please describe it and we will try to implement it.

**Comment by grzanka** [comment]
I'd like to run my executor 10000 times. For each run input parameters should be generated from uniform distribution. How to achieve it ?

**Comment by dkrol** [comment]
We fixed the problem. Right now you just need to set parametrization to random value - gauss, specify distribution parameters and specify replication level to 1000. Each simulation run will get new random value.
